In [26]:
import pandas as pd
import shapefile
import matplotlib.pyplot as plt
import geopandas as gpd
import pysal as ps
import pylab as plot
import numpy as np
import pickle
import geocoder

from shapely.geometry import shape


%matplotlib inline
pd.options.mode.chained_assignment = None  # default='warn'

In [3]:
gdf_medicare = pd.read_pickle('gdf_medicare')

In [39]:
gdf_medicare.head()

,DRG Definition,Provider Id,Provider Name,Provider Street Address,Provider City,Provider State,Provider Zip Code,Hospital Referral Region Description,Total Discharges,Average Covered Charges,Average Total Payments,Average Medicare Payments,long_lat,geometry,city_state
0,039 - EXTRACRANIAL PROCEDURES W/O CC/MCC,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,AL - Dothan,91,"$32,963.07","$5,777.24","$4,763.73","(-85.3928604125977, 31.2167854309082)",POINT (-85.3928604125977 31.2167854309082),"DOTHAN, AL"
1,039 - EXTRACRANIAL PROCEDURES W/O CC/MCC,10005,MARSHALL MEDICAL CENTER SOUTH,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,AL - Birmingham,14,"$15,131.85","$5,787.57","$4,976.71","(-86.3727798461914, 34.1399955749512)",POINT (-86.37277984619141 34.1399955749512),"BOAZ, AL"
2,039 - EXTRACRANIAL PROCEDURES W/O CC/MCC,10006,ELIZA COFFEE MEMORIAL HOSPITAL,205 MARENGO STREET,FLORENCE,AL,35631,AL - Birmingham,24,"$37,560.37","$5,434.95","$4,453.79","(-87.6751022338867, 34.8017730712891)",POINT (-87.6751022338867 34.8017730712891),"FLORENCE, AL"
3,039 - EXTRACRANIAL PROCEDURES W/O CC/MCC,10011,ST VINCENT'S EAST,50 MEDICAL PARK EAST DRIVE,BIRMINGHAM,AL,35235,AL - Birmingham,25,"$13,998.28","$5,417.56","$4,129.16","(-86.636100769043, 33.6505241394043)",POINT (-86.636100769043 33.6505241394043),"BIRMINGHAM, AL"
4,039 - EXTRACRANIAL PROCEDURES W/O CC/MCC,10016,SHELBY BAPTIST MEDICAL CENTER,1000 FIRST STREET NORTH,ALABASTER,AL,35007,AL - Birmingham,18,"$31,633.27","$5,658.33","$4,851.44","(-86.8290939331055, 33.2154388427734)",POINT (-86.8290939331055 33.2154388427734),"ALABASTER, AL"

In [16]:
gdf_medicare['city_state'] = gdf_medicare['Provider City'] + ', ' + gdf_medicare['Provider State']

In [42]:
gdf_hrr = pd.read_pickle('Dataframes/gdf_hrr')

In [43]:
gdf_hrr.head()

,HRRCITY,HRRNUM,HRR_BDRY_I,geometry
0,AL- BIRMINGHAM,1,1,"(POLYGON ((-85.89658 32.70483, -85.90771000000..."
1,AL- DOTHAN,2,2,"(POLYGON ((-86.194 31.43991, -86.1947800000000..."
2,AL- HUNTSVILLE,5,3,"(POLYGON ((-86.69474000000001 34.42309, -86.71..."
3,AL- MOBILE,6,4,"(POLYGON ((-87.55554000000001 30.47282, -87.56..."
4,AL- MONTGOMERY,7,5,"POLYGON ((-86.49925 31.52517, -86.642280000000..."